#
#   gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: xam_development
  pool: 5
  username: xam
  password:

production:
  <<: *default
  database: xam_prod

development:
  <<: *default
  database: xam_dev

test:
  <<: *default
  database: xam_test

